// src/app/neighborhoods/henderson/page.tsx
import type { Metadata } from 'next';
import RealScoutListings from '@/components/RealScoutListings';
import { Home, MapPin, School, ShoppingBag, Mountain } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Henderson Homes for Sale | Dr. Jan Duffy Real Estate | Las Vegas',
  description:
    'Find your dream home in Henderson, NV. Family-friendly community with excellent schools, parks, and amenities. Expert guidance from Dr. Jan Duffy. Call 702-222-1964.',
  keywords: [
    'Henderson homes for sale',
    'Henderson real estate',
    'Henderson NV',
    'Henderson neighborhoods',
    'Henderson homes',
    'Henderson properties',
    'Henderson family community',
    'Henderson schools',
    'Henderson amenities',
    'Henderson parks',
    'Henderson shopping',
    'Henderson home prices',
    'Henderson real estate market',
    'Henderson home buying',
    'Henderson home selling',
    'Las Vegas Henderson',
    'Henderson real estate agent',
    'Henderson realtor',
    'Green Valley Henderson',
    'Anthem Henderson',
  ],
  openGraph: {
    title: 'Henderson Homes for Sale | Dr. Jan Duffy Real Estate | Las Vegas',
    description: 'Find your dream home in Henderson, NV. Family-friendly community with excellent schools, parks, and amenities.',
    url: 'https://drjanetduffy.com/neighborhoods/henderson',
    type: 'website',
  },
  alternates: {
    canonical: '/neighborhoods/henderson',
  },
};

const HendersonPage = () => {
  const features = [
    {
      icon: School,
      title: 'Excellent Schools',
      description: 'Top-rated public schools including Green Valley High School and Coronado High School',
    },
    {
      icon: Mountain,
      title: 'Natural Beauty',
      description: 'Close to Lake Mead, Red Rock Canyon, and numerous hiking trails',
    },
    {
      icon: ShoppingBag,
      title: 'Shopping & Dining',
      description: 'The District at Green Valley Ranch, Galleria at Sunset, and diverse dining options',
    },
    {
      icon: Home,
      title: 'Family-Friendly',
      description: 'Safe neighborhoods with parks, community centers, and family activities',
    },
  ];

  return (
    <div className="pt-16">
      {/* Hero Section */}
      <section className="section-padding bg-gradient-to-br from-vegas-deep-blue to-vegas-accent-blue text-white">
        <div className="container-max">
          <div className="text-center max-w-4xl mx-auto">
            <h1 className="text-4xl md:text-5xl font-bold mb-6">
              Henderson Homes for Sale
            </h1>
            <p className="text-xl text-gray-200 mb-8 leading-relaxed">
              Discover Henderson, Nevada's family-friendly community with excellent schools,
              beautiful parks, and a strong sense of community. Perfect for families and professionals.
            </p>
            <a
              href="tel:702-222-1964"
              className="btn-primary inline-flex items-center space-x-2"
            >
              <span>Call 702-222-1964</span>
            </a>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="section-padding bg-white">
        <div className="container-max">
          <h2 className="text-3xl md:text-4xl font-bold text-vegas-deep-blue text-center mb-12">
            Why Choose Henderson?
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <div key={index} className="text-center">
                  <div className="w-16 h-16 bg-vegas-gold rounded-full flex items-center justify-center mx-auto mb-4">
                    <Icon className="w-8 h-8 text-vegas-deep-blue" />
                  </div>
                  <h3 className="text-xl font-semibold text-vegas-deep-blue mb-3">
                    {feature.title}
                  </h3>
                  <p className="text-gray-600 leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* RealScout Listings */}
      <section className="section-padding bg-gray-50">
        <RealScoutListings />
      </section>

      {/* CTA Section */}
      <section className="section-padding bg-gradient-to-r from-vegas-deep-blue to-vegas-accent-blue text-white">
        <div className="container-max text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-6">
            Ready to Find Your Henderson Home?
          </h2>
          <p className="text-xl mb-8 opacity-90 max-w-3xl mx-auto">
            Let Dr. Jan Duffy help you find the perfect home in Henderson.
            From Green Valley to Anthem, I know every neighborhood.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <a
              href="tel:702-222-1964"
              className="btn-primary inline-flex items-center justify-center"
            >
              Call 702-222-1964
            </a>
            <a
              href="/contact"
              className="btn-secondary inline-flex items-center justify-center"
            >
              Schedule Consultation
            </a>
          </div>
        </div>
      </section>
    </div>
  );
};

export default HendersonPage;

// legacy-sveltekit/src/routes/communities/henderson/+page.svelte
<script lang="ts">
	import { MapPin, Home, Award, TrendingUp, DollarSign, Users, CheckCircle, Shield } from 'lucide-svelte';
	import { onMount } from 'svelte';
	import { browser } from '$app/environment';

	interface TocItem {
		id: string;
		label: string;
	}

	const features: string[] = [
		'Family-friendly community',
		'Excellent schools',
		'Safe neighborhoods',
		'Growing economy',
		'Parks and recreation',
		'Community events',
		'Affordable housing',
		'Strong job market'
	];

	const tocItems: TocItem[] = [
		{ id: 'overview', label: 'Overview' },
		{ id: 'benefits', label: 'Key Benefits' },
		{ id: 'properties', label: 'Available Properties' },
		{ id: 'cta', label: 'Work With Dr. Duffy' }
	];

	let mounted = false;

	onMount(() => {
		mounted = true;
	});
</script>

<svelte:head>
	<title>Henderson Luxury &amp; Relocation Real Estate | Dr. Janet Duffy REALTOR®</title>
	<meta name="description" content="Explore Henderson luxury and relocation real estate with Las Vegas Luxury & Relocation REALTOR Dr. Janet Duffy. Discover family-friendly neighborhoods, top schools, and safe communities just outside Las Vegas." />

	<script type="application/ld+json">
	{
		"@context": "https://schema.org",
		"@type": "Place",
		"name": "Henderson, Nevada",
		"description": "Family-friendly city just southeast of Las Vegas with excellent schools, safe neighborhoods, and diverse housing options.",
		"address": {
			"@type": "PostalAddress",
			"addressLocality": "Henderson",
			"addressRegion": "NV",
			"addressCountry": "US"
		}
	}
	</script>
</svelte:head>

<section class="section bg-gradient-to-b from-white via-gray-50 to-white">
	<div class="container-premium">
		<!-- On-page navigation -->
		<nav
			aria-label="Henderson page sections"
			class="mb-10 rounded-full border border-gray-200 bg-white/80 backdrop-blur px-3 py-2 shadow-sm overflow-x-auto scrollbar-hide"
		>
			<ul class="flex items-center gap-2 text-sm whitespace-nowrap">
				{#each tocItems as item}
					<li>
						<a
							href={`#${item.id}`}
							class="inline-flex items-center rounded-full px-3 py-1.5 text-gray-600 hover:text-primary-700 hover:bg-primary-50 transition-colors no-underline"
						>
							{item.label}
						</a>
					</li>
				{/each}
			</ul>
		</nav>

		<div class="text-center mb-16" id="overview">
			<h1 class="font-display text-4xl sm:text-5xl md:text-6xl font-bold mb-6 text-gray-900">
				Discover Homes for Sale in Henderson, Nevada
			</h1>
			<div class="w-24 h-1 bg-gradient-to-r from-transparent via-primary-600 to-transparent mx-auto mb-6"></div>
			<p class="text-xl text-gray-600 max-w-3xl mx-auto leading-relaxed">
				Family-friendly community with excellent schools, safe neighborhoods, and affordable housing
			</p>
		</div>

		<!-- Hero Stats -->
		<div class="grid md:grid-cols-4 gap-6 mb-16">
			<div class="bg-white rounded-xl p-6 shadow-lg text-center">
				<div class="text-3xl font-bold text-primary-600 mb-2">$550K</div>
				<p class="text-gray-600 text-sm">Average Home Price</p>
			</div>
			<div class="bg-white rounded-xl p-6 shadow-lg text-center">
				<div class="text-3xl font-bold text-primary-600 mb-2">320K+</div>
				<p class="text-gray-600 text-sm">Residents</p>
			</div>
			<div class="bg-white rounded-xl p-6 shadow-lg text-center">
				<div class="text-3xl font-bold text-primary-600 mb-2">#2</div>
				<p class="text-gray-600 text-sm">Safest City in Nevada</p>
			</div>
			<div class="bg-white rounded-xl p-6 shadow-lg text-center">
				<div class="text-3xl font-bold text-primary-600 mb-2">A+</div>
				<p class="text-gray-600 text-sm">School Rating</p>
			</div>
		</div>

		<!-- About Henderson -->
		<div class="mb-16">
			<h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-6 text-center">What Makes Henderson a Great Place to Live?</h2>
			<p class="text-lg text-gray-700 mb-8 leading-relaxed max-w-4xl mx-auto text-center">
				Henderson is Nevada's second-largest city and consistently ranked as one of the safest cities in America. Located just southeast of Las Vegas, Henderson offers a family-friendly atmosphere with excellent schools, beautiful parks, affordable housing, and a strong sense of community that makes it an ideal choice for families, professionals, and retirees.
			</p>
		</div>

		<div class="grid md:grid-cols-2 gap-12 mb-16" id="benefits">
			<div class="bg-gradient-to-br from-white to-primary-50/30 rounded-2xl p-10 shadow-lg border border-gray-100">
				<h3 class="text-2xl font-bold text-gray-900 mb-6">Community Overview</h3>
				<p class="text-gray-700 leading-relaxed mb-4">
					Henderson has experienced significant growth while maintaining its small-town feel. The city offers a diverse economy, top-rated schools, and affordable housing options that appeal to a wide range of buyers seeking quality living in the Las Vegas area.
				</p>
				<p class="text-gray-700 leading-relaxed mb-6">
					With over 320,000 residents, Henderson combines urban amenities with suburban comfort, creating an ideal environment for families and professionals seeking excellent schools, safe neighborhoods, and strong community connections.
				</p>
				<ul class="space-y-3">
					{#each features as feature}
						<li class="flex items-start gap-3">
							<CheckCircle class="w-5 h-5 text-green-600 mt-0.5 flex-shrink-0" />
							<span class="text-gray-700">{feature}</span>
						</li>
					{/each}
				</ul>
			</div>

			<div class="bg-gradient-to-br from-white to-primary-50/30 rounded-2xl p-10 shadow-lg border border-gray-100">
				<h3 class="text-2xl font-bold text-gray-900 mb-6">Key Benefits</h3>
				<div class="space-y-6">
					<div class="flex items-start gap-4">
						<div class="flex-shrink-0 w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center">
							<Award class="w-6 h-6 text-primary-600" />
						</div>
						<div>
							<h3 class="text-xl font-bold text-gray-900 mb-2">Top-Rated School District</h3>
							<p class="text-gray-700">A+ rated school district with excellent educational opportunities and high academic performance</p>
						</div>
					</div>
					<div class="flex items-start gap-4">
						<div class="flex-shrink-0 w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center">
							<Shield class="w-6 h-6 text-primary-600" />
						</div>
						<div>
							<h3 class="text-xl font-bold text-gray-900 mb-2">Exceptional Safety Record</h3>
							<p class="text-gray-700">Consistently ranked among the safest cities in Nevada, providing peace of mind for families</p>
						</div>
					</div>
					<div class="flex items-start gap-4">
						<div class="flex-shrink-0 w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center">
							<DollarSign class="w-6 h-6 text-primary-600" />
						</div>
						<div>
							<h3 class="text-xl font-bold text-gray-900 mb-2">Affordable Housing Options</h3>
							<p class="text-gray-700">More affordable than Las Vegas with great value and diverse housing options</p>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Properties in Henderson -->
		<div class="mb-16" id="properties">
			<h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-6 text-center">What Properties Are Available in Henderson?</h2>
			<p class="text-lg text-gray-700 mb-8 leading-relaxed max-w-4xl mx-auto text-center">
				Henderson offers diverse property types including single-family homes, townhomes, condos, and luxury estates. Properties range from affordable starter homes to upscale properties, all within safe neighborhoods with excellent schools and community amenities.
			</p>
			{#if mounted && browser}
				<div class="realscout-wrapper">
					<realscout-office-listings 
						agent-encoded-id="QWdlbnQtMjI1MDUw"
						sort-order="STATUS_AND_SIGNIFICANT_CHANGE"
						listing-status="For Sale"
						property-types="SFR,MF,TC"
						max-results="6">
					</realscout-office-listings>
				</div>
			{:else}
				<div class="loading-skeleton">
					<div class="grid md:grid-cols-3 gap-6">
						{#each Array(3) as _}
							<div class="animate-pulse bg-white rounded-2xl shadow-lg overflow-hidden">
								<div class="bg-gray-200 h-64"></div>
								<div class="p-6 space-y-4">
									<div class="h-6 bg-gray-200 rounded w-3/4"></div>
									<div class="h-5 bg-gray-200 rounded w-1/2"></div>
								</div>
							</div>
						{/each}
					</div>
				</div>
			{/if}
			<div class="text-center mt-8">
				<a href="/properties?neighborhood=henderson" class="btn-primary">View All Henderson Properties</a>
			</div>
		</div>

		<!-- CTA Section -->
		<div class="bg-gradient-to-r from-primary-600 to-primary-700 rounded-2xl p-12 text-center text-white" id="cta">
			<h2 class="text-3xl md:text-4xl font-bold mb-4">Ready to Find Your Dream Home in Henderson?</h2>
			<p class="text-lg text-white text-opacity-90 mb-8 max-w-2xl mx-auto">
				Let me help you find your perfect home in Henderson. With deep knowledge of the city's neighborhoods, schools, and market conditions, I'll guide you through every step of your home buying journey.
			</p>
			<div class="flex flex-col sm:flex-row gap-4 justify-center">
				<a href="/contact" class="btn-primary bg-white text-primary-600 hover:bg-gray-100">Contact Me</a>
				<a href="/properties?neighborhood=henderson" class="btn-secondary border-white text-white hover:bg-white hover:text-primary-600">View Properties</a>
			</div>
		</div>
	</div>
</section>

<style>
	.realscout-wrapper {
		min-height: 400px;
		width: 100%;
		contain: layout style paint;
		position: relative;
	}

	.loading-skeleton {
		min-height: 400px;
		width: 100%;
	}
</style>
