// src/routes/about/+page.svelte
<script>
import SEO from '$lib/components/SEO.svelte';

// This could be expanded to load dynamic content from a CMS
const achievements = [
  {
    title: '150+ Properties Sold',
    description: 'Successfully closed transactions across Las Vegas',
  },
  {
    title: '$50M+ Sales Volume',
    description: 'Total value of properties sold',
  },
  {
    title: '15 Years Experience',
    description: 'Dedicated real estate expertise',
  },
  {
    title: '98% Client Satisfaction',
    description: 'Based on client feedback and reviews',
  },
];

const services = [
  'Residential Sales & Purchases',
  'Luxury Home Specialization',
  'First-Time Buyer Guidance',
  'Investment Property Consulting',
  'Market Analysis & Pricing',
  'Negotiation & Transaction Management',
  'Rental Property Management',
  'Relocation Services',
];

const certifications = [
  'Licensed REALTOR in Nevada',
  'Certified Residential Specialist (CRS)',
  "Accredited Buyer's Representative (ABR)",
  'Graduate, REALTOR Institute (GRI)',
  'Luxury Home Marketing Specialist',
  'Certified Negotiation Expert (CNE)',
];

// Breadcrumb schema for SEO
const breadcrumbSchema = {
	'@context': 'https://schema.org',
	'@type': 'BreadcrumbList',
	itemListElement: [
		{
			'@type': 'ListItem',
			position: 1,
			name: 'Home',
			item: 'https://drjanduffy.com'
		},
		{
			'@type': 'ListItem',
			position: 2,
			name: 'About',
			item: 'https://drjanduffy.com/about'
		}
	]
};
</script>

<SEO
	title="About Dr. Jan Duffy | Las Vegas REALTOR® - Experience & Credentials"
	description="Learn about Dr. Jan Duffy, a trusted Las Vegas REALTOR® with 15+ years of experience, 150+ properties sold, and $50M+ in sales volume. CRS, ABR, GRI certified. Specializing in luxury homes, first-time buyers, and investment properties."
	keywords="Dr. Jan Duffy, Las Vegas REALTOR, real estate agent, about, experience, credentials, CRS, ABR, GRI, luxury home specialist"
	url="https://drjanduffy.com/about"
	type="profile"
	schema={breadcrumbSchema}
/>

<div class="container mx-auto px-4 py-8">
	<!-- Hero Section -->
	<div class="text-center mb-16">
		<div class="w-32 h-32 bg-primary-600 rounded-full flex items-center justify-center mx-auto mb-6">
			<span class="text-white font-bold text-4xl">JD</span>
		</div>
		<h1 class="text-4xl font-bold mb-4 text-gray-800">Dr. Jan Duffy</h1>
		<p class="text-xl text-primary-600 font-semibold mb-4">Licensed REALTOR</p>
		<p class="text-lg text-gray-600 max-w-3xl mx-auto">
			Your trusted Las Vegas real estate expert with over 15 years of experience helping clients buy, sell, and invest in properties throughout the greater Las Vegas area.
		</p>
	</div>
	
	<!-- About Story -->
	<div class="max-w-4xl mx-auto mb-16">
		<div class="grid md:grid-cols-2 gap-12 items-center">
			<div>
				<h2 class="text-3xl font-bold mb-6 text-gray-800">My Story</h2>
				<div class="space-y-4 text-gray-600">
					<p>
						With over 15 years of experience in the Las Vegas real estate market, I've built a reputation for delivering exceptional results and personalized service. My journey in real estate began with a passion for helping people find their perfect home and has evolved into a comprehensive practice serving buyers, sellers, and investors.
					</p>
					<p>
						I understand that buying or selling a home is one of life's most significant decisions. That's why I'm committed to providing expert guidance, market insights, and unwavering support throughout every step of the process. My clients trust me not just for my expertise, but for my integrity, attention to detail, and genuine care for their success.
					</p>
					<p>
						Based in Las Vegas, I have an intimate knowledge of local neighborhoods, market trends, and the unique characteristics that make each area special. Whether you're a first-time buyer, seasoned investor, or looking to sell your current home, I'm here to help you achieve your real estate goals.
					</p>
				</div>
			</div>
			<div class="bg-gray-50 rounded-lg p-8">
				<h3 class="text-xl font-semibold mb-4 text-gray-800">Quick Facts</h3>
				<ul class="space-y-3">
					<li class="text-gray-600">• Las Vegas native</li>
					<li class="text-gray-600">• 15+ years in real estate</li>
					<li class="text-gray-600">• Luxury home specialist</li>
					<li class="text-gray-600">• Investment property expert</li>
					<li class="text-gray-600">• Available 7 days a week</li>
				</ul>
			</div>
		</div>
	</div>
	
	<!-- Achievements -->
	<div class="mb-16">
		<h2 class="text-3xl font-bold text-center mb-12 text-gray-800">My Achievements</h2>
		<div class="grid md:grid-cols-4 gap-8">
			{#each achievements as achievement}
				<div class="text-center">
					<h3 class="text-xl font-semibold mb-2 text-gray-800">{achievement.title}</h3>
					<p class="text-gray-600">{achievement.description}</p>
				</div>
			{/each}
		</div>
	</div>
	
	<!-- Services -->
	<div class="mb-16">
		<h2 class="text-3xl font-bold text-center mb-12 text-gray-800">Services I Provide</h2>
		<div class="max-w-4xl mx-auto">
			<div class="grid md:grid-cols-2 gap-6">
				{#each services as service}
					<div>
						<span class="text-gray-700">{service}</span>
					</div>
				{/each}
			</div>
		</div>
	</div>
	
	<!-- Certifications -->
	<div class="mb-16">
		<h2 class="text-3xl font-bold text-center mb-12 text-gray-800">Professional Certifications</h2>
		<div class="max-w-4xl mx-auto">
			<div class="grid md:grid-cols-2 gap-6">
				{#each certifications as cert}
					<div>
						<span class="text-gray-700">{cert}</span>
					</div>
				{/each}
			</div>
		</div>
	</div>
	
	<!-- Client Testimonials -->
	<div class="mb-16">
		<h2 class="text-3xl font-bold text-center mb-12 text-gray-800">What My Clients Say</h2>
		<div class="grid md:grid-cols-3 gap-8">
			<div class="bg-white rounded-lg shadow-lg p-6">
				<p class="text-gray-600 mb-4">
					"Dr. Duffy made our first home buying experience seamless. Her knowledge of the Las Vegas market and attention to detail helped us find the perfect home within our budget."
				</p>
				<div class="font-semibold text-gray-800">Sarah & Mike Johnson</div>
				<div class="text-sm text-gray-500">First-time Buyers</div>
			</div>
			
			<div class="bg-white rounded-lg shadow-lg p-6">
				<p class="text-gray-600 mb-4">
					"Jan's expertise in luxury properties is unmatched. She helped us sell our home for 15% above asking price and found us an incredible investment property."
				</p>
				<div class="font-semibold text-gray-800">Robert Chen</div>
				<div class="text-sm text-gray-500">Luxury Home Seller & Investor</div>
			</div>
			
			<div class="bg-white rounded-lg shadow-lg p-6">
				<p class="text-gray-600 mb-4">
					"Professional, responsive, and results-driven. Jan's market knowledge and negotiation skills saved us thousands on our home purchase."
				</p>
				<div class="font-semibold text-gray-800">Lisa Martinez</div>
				<div class="text-sm text-gray-500">Relocating from California</div>
			</div>
		</div>
	</div>
	
	<!-- CTA Section -->
	<div class="bg-primary-600 text-white rounded-lg p-8 text-center">
		<h2 class="text-2xl font-bold mb-4">Ready to Work Together?</h2>
		<p class="text-lg mb-6">
			Let's discuss your real estate goals and how I can help you achieve them. I'm here to provide expert guidance every step of the way.
		</p>
		<div class="flex flex-col sm:flex-row gap-4 justify-center">
			<a href="/contact" class="bg-white text-primary-600 px-8 py-3 rounded-lg font-semibold hover:bg-gray-100 transition-colors">
				Get in Touch
			</a>
			<a href="tel:+17025551234" class="border-2 border-white text-white px-8 py-3 rounded-lg font-semibold hover:bg-white hover:text-primary-600 transition-colors">
				Call (702) 555-1234
			</a>
		</div>
	</div>
</div>

// src/app/about/page.tsx
import { Award, CheckCircle, Heart, Home, Star, Users } from 'lucide-react';
import type { Metadata } from 'next';
import RealScoutListings from '@/components/RealScoutListings';

export const metadata: Metadata = {
  title: 'About Dr. Jan Duffy | Las Vegas Real Estate Expert | 20+ Years Experience',
  description:
    'Meet Dr. Jan Duffy, Las Vegas native and real estate expert with 20+ years experience. 500+ happy clients helped find homes in Summerlin, Henderson, Green Valley. Call 702-222-1964.',
  keywords: [
    'Dr. Jan Duffy',
    'Las Vegas real estate agent',
    'Las Vegas realtor',
    'real estate experience',
    'Las Vegas neighborhoods',
    'home buying expert',
    'home selling expert',
    'Las Vegas native',
    'Summerlin real estate',
    'Henderson real estate',
    'Green Valley real estate',
    'Las Vegas real estate testimonials',
    'Las Vegas real estate reviews',
    'Las Vegas real estate success stories',
    'Las Vegas real estate agent bio',
    'Las Vegas real estate credentials',
  ],
  openGraph: {
    title: 'About Dr. Jan Duffy | Las Vegas Real Estate Expert | 20+ Years Experience',
    description: 'Meet Dr. Jan Duffy, Las Vegas native and real estate expert with 20+ years experience. 500+ happy clients helped find homes.',
    url: 'https://drjanetduffy.com/about',
    type: 'profile',
  },
  alternates: {
    canonical: '/about',
  },
};

const AboutPage = () => {
  const achievements = [
    {
      icon: Award,
      title: 'Licensed Real Estate Agent',
      description: 'Fully licensed and certified real estate professional in Nevada',
    },
    {
      icon: Users,
      title: '500+ Happy Clients',
      description: 'Successfully helped hundreds of families find their perfect homes',
    },
    {
      icon: Home,
      title: '20+ Years Experience',
      description: 'Deep knowledge of Las Vegas real estate market and trends',
    },
    {
      icon: Heart,
      title: 'Personal Touch',
      description: 'Genuine care for your needs throughout the entire process',
    },
  ];

  const testimonials = [
    {
      quote:
        'Dr. Jan made our home buying process so smooth. Her knowledge of Las Vegas neighborhoods is incredible!',
      author: 'Sarah & Mike Johnson',
      location: 'Summerlin',
      rating: 5,
    },
    {
      quote:
        "We couldn't have asked for a better real estate agent. Jan truly cares about her clients.",
      author: 'David Chen',
      location: 'Henderson',
      rating: 5,
    },
    {
      quote: "Jan's expertise helped us sell our home above asking price in just 3 days!",
      author: 'Lisa Rodriguez',
      location: 'Green Valley',
      rating: 5,
    },
  ];

  return (
    <div className="pt-16">
      {/* Hero Section */}
      <section className="section-padding bg-gradient-to-br from-vegas-deep-blue to-vegas-accent-blue text-white">
        <div className="container-max">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <h1 className="text-4xl md:text-5xl font-bold mb-6">About Dr. Jan Duffy</h1>
              <p className="text-xl text-gray-200 mb-8 leading-relaxed">
                As a Las Vegas native with over 20 years of real estate experience, I've dedicated
                my career to helping families find their perfect homes in the vibrant communities of
                Las Vegas.
              </p>
              <div className="flex flex-col sm:flex-row gap-4">
                <a
                  href="tel:702-222-1964"
                  className="btn-primary inline-flex items-center justify-center"
                >
                  Call 702-222-1964
                </a>
                <a
                  href="/contact"
                  className="btn-secondary inline-flex items-center justify-center"
                >
                  Get in Touch
                </a>
              </div>
            </div>

            <div className="relative">
              <div className="bg-white/10 backdrop-blur-sm rounded-2xl p-8 border border-white/20">
                <div className="aspect-square bg-gradient-to-br from-vegas-gold/20 to-vegas-gold/40 rounded-xl flex items-center justify-center">
                  <div className="text-center">
                    <div className="w-32 h-32 bg-vegas-gold rounded-full mx-auto mb-4 flex items-center justify-center">
                      <span className="text-4xl font-bold text-vegas-deep-blue">JD</span>
                    </div>
                    <h3 className="text-2xl font-bold text-white mb-2">Dr. Jan Duffy</h3>
                    <p className="text-vegas-gold font-semibold">Las Vegas Real Estate Expert</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Story Section */}
      <section className="section-padding bg-white">
        <div className="container-max">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl md:text-4xl font-bold text-vegas-deep-blue text-center mb-12">
              My Story
            </h2>

            <div className="prose prose-lg max-w-none">
              <p className="text-lg text-gray-600 mb-6 leading-relaxed">
                Born and raised in Las Vegas, I've witnessed the incredible growth and
                transformation of our city over the past two decades. What started as a passion for
                helping people find their perfect home has evolved into a career dedicated to making
                the real estate process as smooth and enjoyable as possible.
              </p>

              <p className="text-lg text-gray-600 mb-6 leading-relaxed">
                My approach is simple: be the expert neighbor who knows every sale and genuinely
                helps. I believe that buying or selling a home should be an exciting journey, not a
                stressful experience. That's why I take the time to understand your unique needs,
                preferences, and goals.
              </p>

              <p className="text-lg text-gray-600 mb-8 leading-relaxed">
                With deep knowledge of every neighborhood, school district, and community in Las
                Vegas, I can help you find not just a house, but a home where you'll create lasting
                memories. Whether you're a first-time buyer, looking to upgrade, or ready to
                downsize, I'm here to guide you every step of the way.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Achievements */}
      <section className="section-padding bg-gray-50">
        <div className="container-max">
          <h2 className="text-3xl md:text-4xl font-bold text-vegas-deep-blue text-center mb-12">
            Why Choose Dr. Jan Duffy?
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {achievements.map((achievement, index) => {
              const Icon = achievement.icon;
              return (
                <div key={index} className="text-center">
                  <div className="w-16 h-16 bg-vegas-gold rounded-full flex items-center justify-center mx-auto mb-4">
                    <Icon className="w-8 h-8 text-vegas-deep-blue" />
                  </div>
                  <h3 className="text-xl font-semibold text-vegas-deep-blue mb-3">
                    {achievement.title}
                  </h3>
                  <p className="text-gray-600 leading-relaxed">{achievement.description}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="section-padding bg-white">
        <div className="container-max">
          <h2 className="text-3xl md:text-4xl font-bold text-vegas-deep-blue text-center mb-12">
            What My Clients Say
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <div key={index} className="bg-gray-50 rounded-xl p-6 border border-gray-200">
                <div className="flex items-center mb-4">
                  {[...Array(testimonial.rating)].map((_, i) => (
                    <Star key={i} className="w-5 h-5 text-vegas-gold fill-current" />
                  ))}
                </div>
                <p className="text-gray-700 mb-4 italic leading-relaxed">"{testimonial.quote}"</p>
                <div className="border-t border-gray-200 pt-4">
                  <p className="font-semibold text-vegas-deep-blue">{testimonial.author}</p>
                  <p className="text-sm text-gray-500">{testimonial.location}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* RealScout Listings */}
      <section className="section-padding bg-gray-50">
        <RealScoutListings />
      </section>

      {/* CTA Section */}
      <section className="section-padding bg-gradient-to-r from-vegas-deep-blue to-vegas-accent-blue text-white">
        <div className="container-max text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-6">Ready to Work Together?</h2>
          <p className="text-xl mb-8 opacity-90 max-w-3xl mx-auto">
            Let's discuss your real estate goals and how I can help you achieve them. I'm here to
            make your Las Vegas real estate journey smooth and successful.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <a
              href="tel:702-222-1964"
              className="btn-primary inline-flex items-center justify-center"
            >
              Call 702-222-1964
            </a>
            <a href="/contact" className="btn-secondary inline-flex items-center justify-center">
              Send a Message
            </a>
          </div>
        </div>
      </section>
    </div>
  );
};

export default AboutPage;
