// legacy-sveltekit/src/lib/components/Footer.svelte
<script>
	import { Mail, MapPin } from 'lucide-svelte';
	
	const currentYear = new Date().getFullYear();
	
	let newsletterEmail = '';
	let newsletterSubmitted = false;
	let newsletterError = false;
	
	function handleNewsletterSubmit() {
		if (!newsletterEmail || !newsletterEmail.includes('@')) {
			newsletterError = true;
			return;
		}
		
		// In a real implementation, this would send to your email service
		// For now, we'll just show a success message
		newsletterSubmitted = true;
		newsletterError = false;
		newsletterEmail = '';
		
		// Reset success message after 5 seconds
		setTimeout(() => {
			newsletterSubmitted = false;
		}, 5000);
	}
	
	const mainLinks = [
		{ name: 'Home', href: '/' },
		{ name: 'Properties', href: '/properties' },
		{ name: 'About', href: '/about' },
		{ name: 'Services', href: '/services' },
		{ name: 'Neighborhoods', href: '/neighborhoods' },
		{ name: 'Testimonials', href: '/testimonials' },
		{ name: 'Market Insights', href: '/market-insights' },
		{ name: 'Contact', href: '/contact' },
		{ name: 'Blog', href: '/blog' }
	];
	
	const propertyLinks = [
		{ name: 'Rentals', href: '/rentals' },
		{ name: 'Grid View', href: '/listings-embedded' },
		{ name: 'List View', href: '/listings-list' },
		{ name: 'Past Sales', href: '/past-sales' },
		{ name: 'Single Family', href: '/property-types/single-family' },
		{ name: 'Condos', href: '/property-types/condos' },
		{ name: 'Townhomes', href: '/property-types/townhomes' },
		{ name: 'New Construction', href: '/property-types/new-construction' },
		{ name: 'Luxury Estates', href: '/property-types/luxury-homes' },
		{ name: 'Gated Communities', href: '/property-types/gated-communities' },
		{ name: 'Golf Communities', href: '/property-types/golf-communities' },
		{ name: '55+ Communities', href: '/property-types/55-plus-communities' },
		{ name: 'Foreclosures', href: '/property-types/foreclosures' },
		{ name: 'Short Sales', href: '/property-types/short-sales' }
	];
	
	const communityLinks = [
		{ name: 'Summerlin', href: '/communities/summerlin' },
		{ name: 'Henderson', href: '/communities/henderson' },
		{ name: 'Green Valley', href: '/communities/green-valley' },
		{ name: 'North Las Vegas', href: '/communities/north-las-vegas' },
		{ name: 'Boulder City', href: '/communities/boulder-city' },
		{ name: 'Seven Hills', href: '/communities/seven-hills' },
		{ name: 'Southern Highlands', href: '/communities/southern-highlands' },
		{ name: 'Mountains Edge', href: '/communities/mountains-edge' },
		{ name: 'Anthem', href: '/communities/anthem' }
	];
	
	const serviceLinks = [
		{ name: 'All Services', href: '/services' },
		{ name: 'Home Value', href: '/home-value' },
		{ name: 'Buying Guide', href: '/buying-guide' },
		{ name: 'Selling Guide', href: '/selling-guide' },
		{ name: 'First-Time Buyers', href: '/first-time-buyers' },
		{ name: 'Investment Guide', href: '/investment-guide' },
		{ name: 'Relocation', href: '/relocation' },
		{ name: 'Resources', href: '/resources' },
		{ name: 'FAQ', href: '/faq' },
		{ name: 'Mortgage Calculator', href: '/mortgage-calculator' },
		{ name: 'Testimonials', href: '/testimonials' },
		{ name: 'Market Insights', href: '/market-insights' },
		{ name: 'Contact', href: '/contact' }
	];
</script>

<footer class="bg-gray-900 text-white">
	<div class="container mx-auto px-4 sm:px-6 lg:px-8">
		<div class="py-12 lg:py-16">
			<div class="flex flex-wrap -mx-4">
				<!-- Main Navigation -->
				<div class="w-full sm:w-1/2 lg:w-1/5 px-4 mb-8 lg:mb-0">
					<h3 class="text-lg font-bold mb-4 text-white">Main</h3>
					<ul class="space-y-2.5">
						{#each mainLinks as link}
							<li>
								<a 
									href={link.href} 
									class="text-gray-300 hover:text-primary-400 transition-colors text-sm"
								>
									{link.name}
								</a>
							</li>
						{/each}
					</ul>
				</div>
				
				<!-- Properties -->
				<div class="w-full sm:w-1/2 lg:w-1/5 px-4 mb-8 lg:mb-0">
					<h3 class="text-lg font-bold mb-4 text-white">Properties</h3>
					<ul class="space-y-2.5">
						{#each propertyLinks as link}
							<li>
								<a 
									href={link.href} 
									class="text-gray-300 hover:text-primary-400 transition-colors text-sm"
								>
									{link.name}
								</a>
							</li>
						{/each}
					</ul>
				</div>
				
				<!-- Communities -->
				<div class="w-full sm:w-1/2 lg:w-1/5 px-4 mb-8 lg:mb-0">
					<h3 class="text-lg font-bold mb-4 text-white">Communities</h3>
					<p class="text-sm text-gray-400 mb-3">Popular Neighborhoods</p>
					<ul class="space-y-2.5 mb-4">
						{#each communityLinks as link}
							<li>
								<a 
									href={link.href} 
									class="text-gray-300 hover:text-primary-400 transition-colors text-sm"
								>
									{link.name}
								</a>
							</li>
						{/each}
					</ul>
					<a 
						href="/neighborhoods" 
						class="text-primary-400 hover:text-primary-300 font-semibold text-sm inline-flex items-center gap-1 transition-colors"
					>
						View All →
					</a>
				</div>
				
				<!-- Services -->
				<div class="w-full sm:w-1/2 lg:w-1/5 px-4 mb-8 lg:mb-0">
					<h3 class="text-lg font-bold mb-4 text-white">Services</h3>
					<ul class="space-y-2.5">
						{#each serviceLinks as link}
							<li>
								<a 
									href={link.href} 
									class="text-gray-300 hover:text-primary-400 transition-colors text-sm"
								>
									{link.name}
								</a>
							</li>
						{/each}
					</ul>
				</div>
				
				<!-- Contact Information -->
				<div class="w-full sm:w-1/2 lg:w-1/5 px-4 mb-8 lg:mb-0">
					<div class="flex items-center space-x-3 mb-6">
						<div class="w-12 h-12 bg-primary-600 rounded-full flex items-center justify-center flex-shrink-0">
							<span class="text-white font-bold text-lg">JD</span>
						</div>
						<div>
							<h3 class="text-xl font-bold text-white">Dr. Janet Duffy</h3>
							<p class="text-sm text-gray-400">REALTOR<sup>®</sup></p>
						</div>
					</div>
					
					<div class="space-y-4">
						<div class="flex items-start gap-3">
							<div>
								<p class="text-sm text-gray-400 mb-1">Phone</p>
								<a 
									href="tel:+17027667668" 
									class="text-gray-300 hover:text-primary-400 transition-colors text-sm font-medium"
								>
									(702) 766-7668
								</a>
							</div>
						</div>
						
						<div class="flex items-start gap-3">
							<Mail class="w-4 h-4 text-primary-400 mt-0.5 flex-shrink-0" />
							<div>
								<p class="text-sm text-gray-400 mb-1">Email</p>
								<a 
									href="mailto:info@DrJanetDuffy.com" 
									class="text-gray-300 hover:text-primary-400 transition-colors text-sm font-medium break-all"
								>
									info@DrJanetDuffy.com
								</a>
							</div>
						</div>
						
						<div class="flex items-start gap-3">
							<MapPin class="w-4 h-4 text-primary-400 mt-0.5 flex-shrink-0" />
							<div>
								<p class="text-sm text-gray-400 mb-1">Office Location</p>
								<address class="text-gray-300 text-sm not-italic leading-relaxed">
									1980 Festival Plaza Drive, Suite 300<br />
									Las Vegas, NV 89135
								</address>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<!-- Newsletter Signup Section -->
			<div class="border-t border-gray-800 pt-12 pb-8">
				<div class="max-w-2xl mx-auto text-center">
					<h3 class="text-2xl font-bold text-white mb-2">Stay in the Know</h3>
					<p class="text-gray-400 mb-6">Get the latest Las Vegas real estate insights and market updates delivered to your inbox.</p>
					<form class="flex flex-col sm:flex-row gap-3 max-w-md mx-auto" on:submit|preventDefault={handleNewsletterSubmit}>
						<input
							type="email"
							placeholder="Email:"
							bind:value={newsletterEmail}
							required
							class="flex-1 px-4 py-3 bg-gray-800 border border-gray-700 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent {newsletterError ? 'border-red-500' : ''}"
						/>
						<button
							type="submit"
							class="px-6 py-3 bg-gold-500 hover:bg-gold-600 text-white font-semibold rounded-lg transition-colors whitespace-nowrap disabled:opacity-50 disabled:cursor-not-allowed"
							disabled={newsletterSubmitted}
						>
							{newsletterSubmitted ? 'Subscribed!' : 'Subscribe'}
						</button>
					</form>
					{#if newsletterSubmitted}
						<p class="text-green-400 text-sm mt-3">Thank you for subscribing!</p>
					{/if}
					{#if newsletterError}
						<p class="text-red-400 text-sm mt-3">Please enter a valid email address.</p>
					{/if}
				</div>
			</div>
		</div>
		
		<!-- Bottom Bar -->
		<div class="border-t border-gray-800 pt-8 pb-6">
			<div class="flex flex-col md:flex-row justify-between items-center gap-4">
				<div class="text-sm text-gray-400 text-center md:text-left">
					© {currentYear} Dr. Janet Duffy REALTOR<sup>®</sup>. All rights reserved.
				</div>
				<div class="flex flex-wrap justify-center gap-6 text-sm">
					<a href="/privacy" class="text-gray-400 hover:text-primary-400 transition-colors">Privacy Policy</a>
					<a href="/terms" class="text-gray-400 hover:text-primary-400 transition-colors">Terms of Service</a>
					<a href="/sitemap" class="text-gray-400 hover:text-primary-400 transition-colors">Sitemap</a>
				</div>
			</div>
		</div>
	</div>
</footer>

// src/components/Footer.tsx
import { Facebook, Instagram, Linkedin, Mail, MapPin, Phone } from 'lucide-react';
import Link from 'next/link';

const Footer = () => {
  const currentYear = new Date().getFullYear();

  const quickLinks = [
    { name: 'Home', href: '/' },
    { name: 'Buy Homes', href: '/buy' },
    { name: 'Sell Homes', href: '/sell' },
    { name: 'AI Tools', href: '/ai-tools' },
    { name: 'About Dr. Jan', href: '/about' },
    { name: 'Contact', href: '/contact' },
  ];

  const services = [
    { name: 'Home Buying', href: '/buy' },
    { name: 'Home Selling', href: '/sell' },
    { name: 'Market Analysis', href: '/market-analysis' },
    { name: 'Property Valuation', href: '/valuation' },
    { name: 'Investment Properties', href: '/investment' },
  ];

  const neighborhoods = [
    { name: 'Summerlin', href: '/neighborhoods/summerlin' },
    { name: 'Henderson', href: '/neighborhoods/henderson' },
    { name: 'Green Valley', href: '/neighborhoods/green-valley' },
    { name: 'Anthem', href: '/neighborhoods/anthem' },
    { name: 'Southern Highlands', href: '/neighborhoods/southern-highlands' },
  ];

  return (
    <footer className="bg-luxury-navy text-white">
      <div className="container-max">
        {/* Main Footer Content */}
        <div className="section-padding">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {/* Company Info */}
            <div className="lg:col-span-1">
              <div className="flex items-center space-x-2 mb-4">
                <div className="w-10 h-10 bg-luxury-gold rounded-full flex items-center justify-center shadow-lg">
                  <span className="text-luxury-navy font-bold text-lg">JD</span>
                </div>
                <div>
                  <h3 className="text-xl font-bold">Dr. Jan Duffy</h3>
                  <p className="text-luxury-gold text-sm">Las Vegas Real Estate Expert 🎰</p>
                </div>
              </div>
              <p className="text-gray-300 mb-4">
                Be the expert neighbor who knows every sale and genuinely helps. 20+ years of Las
                Vegas real estate expertise.
              </p>

              {/* Contact Info */}
              <div className="space-y-2">
                <a
                  href="tel:702-222-1964"
                  className="flex items-center space-x-2 text-luxury-gold hover:text-white transition-colors duration-200"
                >
                  <Phone className="w-4 h-4" />
                  <span>702-222-1964</span>
                </a>
                <a
                  href="mailto:jan@drjanetduffy.com"
                  className="flex items-center space-x-2 text-luxury-gold hover:text-white transition-colors duration-200"
                >
                  <Mail className="w-4 h-4" />
                  <span>jan@drjanetduffy.com</span>
                </a>
                <div className="flex items-center space-x-2 text-gray-300">
                  <MapPin className="w-4 h-4" />
                  <span>Las Vegas, NV</span>
                </div>
              </div>
            </div>

            {/* Quick Links */}
            <div>
              <h4 className="text-lg font-semibold mb-4 text-luxury-gold">Quick Links</h4>
              <ul className="space-y-2">
                {quickLinks.map((link) => (
                  <li key={link.name}>
                    <Link
                      href={link.href}
                      className="text-gray-300 hover:text-luxury-gold transition-colors duration-200"
                    >
                      {link.name}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>

            {/* Services */}
            <div>
              <h4 className="text-lg font-semibold mb-4 text-luxury-gold">Services</h4>
              <ul className="space-y-2">
                {services.map((service) => (
                  <li key={service.name}>
                    <Link
                      href={service.href}
                      className="text-gray-300 hover:text-luxury-gold transition-colors duration-200"
                    >
                      {service.name}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>

            {/* Neighborhoods */}
            <div>
              <h4 className="text-lg font-semibold mb-4 text-luxury-gold">Popular Areas</h4>
              <ul className="space-y-2">
                {neighborhoods.map((neighborhood) => (
                  <li key={neighborhood.name}>
                    <Link
                      href={neighborhood.href}
                      className="text-gray-300 hover:text-luxury-gold transition-colors duration-200"
                    >
                      {neighborhood.name}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>

        {/* Bottom Footer */}
        <div className="border-t border-gray-700 py-6">
          <div className="flex flex-col md:flex-row items-center justify-between px-4 sm:px-6 lg:px-8">
            <div className="text-gray-300 text-sm mb-4 md:mb-0">
              © {currentYear} Dr. Jan Duffy Real Estate. All rights reserved.
            </div>

            {/* Social Media Links */}
            <div className="flex items-center space-x-4">
              <a
                href="https://www.facebook.com/drjanetduffy"
                target="_blank"
                rel="noopener noreferrer"
                className="text-gray-300 hover:text-luxury-gold transition-colors duration-200"
                aria-label="Facebook"
              >
                <Facebook className="w-5 h-5" />
              </a>
              <a
                href="https://www.linkedin.com/in/drjanetduffy"
                target="_blank"
                rel="noopener noreferrer"
                className="text-gray-300 hover:text-luxury-gold transition-colors duration-200"
                aria-label="LinkedIn"
              >
                <Linkedin className="w-5 h-5" />
              </a>
              <a
                href="https://www.instagram.com/drjanetduffy"
                target="_blank"
                rel="noopener noreferrer"
                className="text-gray-300 hover:text-luxury-gold transition-colors duration-200"
                aria-label="Instagram"
              >
                <Instagram className="w-5 h-5" />
              </a>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
