// src/lib/components/Header.svelte
<script>
import { onMount } from 'svelte';
import { browser } from '$app/environment';

let _realScoutReady = false;
let mobileMenuOpen = false;

onMount(() => {
  if (browser) {
    // Wait for RealScout to load - check for any RealScout components
    if (
      window.customElements &&
      (customElements.get('realscout-office-listings') ||
        customElements.get('realscout-advanced-search') ||
        customElements.get('realscout-home-value') ||
        customElements.get('realscout-simple-search') ||
        customElements.get('realscout-your-listings'))
    ) {
      realScoutReady = true;
    } else {
      // Wait for the components to be defined
      const checkInterval = setInterval(() => {
        if (
          window.customElements &&
          (customElements.get('realscout-office-listings') ||
            customElements.get('realscout-advanced-search') ||
            customElements.get('realscout-home-value') ||
            customElements.get('realscout-simple-search') ||
            customElements.get('realscout-your-listings'))
        ) {
          clearInterval(checkInterval);
          _realScoutReady = true;
        }
      }, 100);

      // Timeout after 5 seconds
      setTimeout(() => {
        clearInterval(checkInterval);
        _realScoutReady = true; // Show fallback
      }, 5000);
    }
  }
});

function _toggleMobileMenu() {
  mobileMenuOpen = !mobileMenuOpen;
}
</script>

<header class="bg-white shadow-lg sticky top-0 z-50">
	<!-- Top Bar with Search -->
	<div class="bg-primary-600 text-white py-3">
		<div class="container mx-auto px-4">
			<div class="max-w-4xl mx-auto">
				{#if realScoutReady}
					<realscout-simple-search 
						agent-encoded-id="QWdlbnQtMjI1MDUw">
					</realscout-simple-search>
				{:else}
					<div class="animate-pulse">
						<div class="h-12 bg-primary-500 rounded"></div>
					</div>
				{/if}
			</div>
		</div>
	</div>
	
	<!-- Main Navigation -->
	<nav class="container mx-auto px-4 py-4">
		<div class="flex items-center justify-between">
			<!-- Logo -->
			<div class="flex items-center space-x-2">
				<div class="w-10 h-10 bg-primary-600 rounded-full flex items-center justify-center">
					<span class="text-white font-bold text-lg">JD</span>
				</div>
				<div>
					<h1 class="text-xl font-bold text-gray-800">Dr. Jan Duffy</h1>
					<p class="text-sm text-gray-600">REALTOR</p>
				</div>
			</div>
			
			<!-- Desktop Navigation -->
			<div class="hidden md:flex items-center space-x-8">
				<a 
					href="/" 
					class="text-gray-700 hover:text-primary-600 font-medium transition-colors {$page.url.pathname === '/' ? 'text-primary-600' : ''}"
				>
					Home
				</a>
				<a 
					href="/properties" 
					class="text-gray-700 hover:text-primary-600 font-medium transition-colors {$page.url.pathname === '/properties' ? 'text-primary-600' : ''}"
				>
					Properties
				</a>
				<a 
					href="/home-value" 
					class="text-gray-700 hover:text-primary-600 font-medium transition-colors {$page.url.pathname === '/home-value' ? 'text-primary-600' : ''}"
				>
					Home Value
				</a>
				<a 
					href="/rentals" 
					class="text-gray-700 hover:text-primary-600 font-medium transition-colors {$page.url.pathname === '/rentals' ? 'text-primary-600' : ''}"
				>
					Rentals
				</a>
				<a 
					href="/about" 
					class="text-gray-700 hover:text-primary-600 font-medium transition-colors {$page.url.pathname === '/about' ? 'text-primary-600' : ''}"
				>
					About
				</a>
				<a 
					href="/contact" 
					class="text-gray-700 hover:text-primary-600 font-medium transition-colors {$page.url.pathname === '/contact' ? 'text-primary-600' : ''}"
				>
					Contact
				</a>
				<a 
					href="tel:+17025551234" 
					class="bg-primary-600 text-white px-6 py-2 rounded-lg font-semibold hover:bg-primary-700 transition-colors"
				>
					(702) 555-1234
				</a>
			</div>
			
			<!-- Mobile Menu Button -->
			<button 
				on:click={toggleMobileMenu}
				class="md:hidden p-2 rounded-lg text-gray-700 hover:bg-gray-100 transition-colors"
				aria-label="Toggle mobile menu"
			>
				<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
					<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
				</svg>
			</button>
		</div>
		
		<!-- Mobile Navigation -->
		{#if mobileMenuOpen}
			<div class="md:hidden mt-4 pb-4 border-t border-gray-200">
				<div class="flex flex-col space-y-4 pt-4">
					<a 
						href="/" 
						class="text-gray-700 hover:text-primary-600 font-medium transition-colors {$page.url.pathname === '/' ? 'text-primary-600' : ''}"
						on:click={() => mobileMenuOpen = false}
					>
						Home
					</a>
					<a 
						href="/properties" 
						class="text-gray-700 hover:text-primary-600 font-medium transition-colors {$page.url.pathname === '/properties' ? 'text-primary-600' : ''}"
						on:click={() => mobileMenuOpen = false}
					>
						Properties
					</a>
					<a 
						href="/home-value" 
						class="text-gray-700 hover:text-primary-600 font-medium transition-colors {$page.url.pathname === '/home-value' ? 'text-primary-600' : ''}"
						on:click={() => mobileMenuOpen = false}
					>
						Home Value
					</a>
					<a 
						href="/rentals" 
						class="text-gray-700 hover:text-primary-600 font-medium transition-colors {$page.url.pathname === '/rentals' ? 'text-primary-600' : ''}"
						on:click={() => mobileMenuOpen = false}
					>
						Rentals
					</a>
					<a 
						href="/about" 
						class="text-gray-700 hover:text-primary-600 font-medium transition-colors {$page.url.pathname === '/about' ? 'text-primary-600' : ''}"
						on:click={() => mobileMenuOpen = false}
					>
						About
					</a>
					<a 
						href="/contact" 
						class="text-gray-700 hover:text-primary-600 font-medium transition-colors {$page.url.pathname === '/contact' ? 'text-primary-600' : ''}"
						on:click={() => mobileMenuOpen = false}
					>
						Contact
					</a>
					<a 
						href="tel:+17025551234" 
						class="bg-primary-600 text-white px-6 py-2 rounded-lg font-semibold hover:bg-primary-700 transition-colors text-center"
						on:click={() => mobileMenuOpen = false}
					>
						(702) 555-1234
					</a>
				</div>
			</div>
		{/if}
	</nav>
</header>

// src/components/Header.tsx
'use client';

import { useEffect, useState } from 'react';
import { usePathname } from 'next/navigation';
import Link from 'next/link';

export default function Header() {
  const [realScoutReady, setRealScoutReady] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const pathname = usePathname();

  useEffect(() => {
    if (typeof window !== 'undefined') {
      // Wait for RealScout to load
      if (
        window.customElements &&
        (customElements.get('realscout-office-listings') ||
          customElements.get('realscout-advanced-search') ||
          customElements.get('realscout-home-value') ||
          customElements.get('realscout-simple-search') ||
          customElements.get('realscout-your-listings'))
      ) {
        setRealScoutReady(true);
      } else {
        const checkInterval = setInterval(() => {
          if (
            window.customElements &&
            (customElements.get('realscout-office-listings') ||
              customElements.get('realscout-advanced-search') ||
              customElements.get('realscout-home-value') ||
              customElements.get('realscout-simple-search') ||
              customElements.get('realscout-your-listings'))
          ) {
            clearInterval(checkInterval);
            setRealScoutReady(true);
          }
        }, 100);

        setTimeout(() => {
          clearInterval(checkInterval);
          setRealScoutReady(true);
        }, 5000);
      }
    }
  }, []);

  const navLinks = [
    { href: '/', label: 'Home' },
    { href: '/properties', label: 'Properties' },
    { href: '/home-value', label: 'Home Value' },
    { href: '/rentals', label: 'Rentals' },
    { href: '/about', label: 'About' },
    { href: '/contact', label: 'Contact' }
  ];

  return (
    <header className="bg-white shadow-lg sticky top-0 z-50">
      {/* Top Bar with Search */}
      <div className="bg-primary-600 text-white py-3">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            {realScoutReady ? (
              <div dangerouslySetInnerHTML={{
                __html: '<realscout-simple-search agent-encoded-id="QWdlbnQtMjI1MDUw"></realscout-simple-search>'
              }} />
            ) : (
              <div className="animate-pulse">
                <div className="h-12 bg-primary-500 rounded"></div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Main Navigation */}
      <nav className="container mx-auto px-4 py-4">
        <div className="flex items-center justify-between">
          {/* Logo */}
          <Link href="/" className="flex items-center space-x-2">
            <div className="w-10 h-10 bg-primary-600 rounded-full flex items-center justify-center">
              <span className="text-white font-bold text-lg">JD</span>
            </div>
            <div>
              <h1 className="text-xl font-bold text-gray-800">Dr. Janet Duffy</h1>
              <p className="text-sm text-gray-600">REALTOR<sup>®</sup></p>
            </div>
          </Link>

          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center space-x-8">
            {navLinks.map((link) => (
              <Link
                key={link.href}
                href={link.href}
                className={`font-medium transition-colors ${
                  pathname === link.href
                    ? 'text-primary-600'
                    : 'text-gray-700 hover:text-primary-600'
                }`}
              >
                {link.label}
              </Link>
            ))}
            <a
              href="tel:+17022221964"
              className="bg-primary-600 text-white px-6 py-2 rounded-lg font-semibold hover:bg-primary-700 transition-colors"
            >
              702-222-1964
            </a>
          </div>

          {/* Mobile Menu Button */}
          <button
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            className="md:hidden p-2 rounded-lg text-gray-700 hover:bg-gray-100 transition-colors"
            aria-label="Toggle mobile menu"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16"></path>
            </svg>
          </button>
        </div>

        {/* Mobile Navigation */}
        {mobileMenuOpen && (
          <div className="md:hidden mt-4 pb-4 border-t border-gray-200">
            <div className="flex flex-col space-y-4 pt-4">
              {navLinks.map((link) => (
                <Link
                  key={link.href}
                  href={link.href}
                  className={`font-medium transition-colors ${
                    pathname === link.href
                      ? 'text-primary-600'
                      : 'text-gray-700 hover:text-primary-600'
                  }`}
                  onClick={() => setMobileMenuOpen(false)}
                >
                  {link.label}
                </Link>
              ))}
              <a
                href="tel:+17022221964"
                className="bg-primary-600 text-white px-6 py-2 rounded-lg font-semibold hover:bg-primary-700 transition-colors text-center"
                onClick={() => setMobileMenuOpen(false)}
              >
                702-222-1964
              </a>
            </div>
          </div>
        )}
      </nav>
    </header>
  );
}
