// src/components/MarketInsights.tsx
import { motion } from 'framer-motion';
import { Calendar, DollarSign, Home, TrendingDown, TrendingUp } from 'lucide-react';
import RealScoutListings from './RealScoutListings';

const MarketInsights = () => {
  const marketStats = [
    {
      icon: DollarSign,
      value: '$425,000',
      label: 'Median Home Price',
      change: '+5.2%',
      trend: 'up',
    },
    {
      icon: Home,
      value: '2,847',
      label: 'Active Listings',
      change: '+12.1%',
      trend: 'up',
    },
    {
      icon: Calendar,
      value: '28 days',
      label: 'Avg. Days on Market',
      change: '-8.3%',
      trend: 'down',
    },
    {
      icon: TrendingUp,
      value: '98.5%',
      label: 'List to Sale Ratio',
      change: '+2.1%',
      trend: 'up',
    },
  ];

  const neighborhoods = [
    {
      name: 'Summerlin',
      price: '$650,000',
      change: '+6.2%',
      trend: 'up',
      description: 'Master-planned community with top-rated schools',
    },
    {
      name: 'Henderson',
      price: '$485,000',
      change: '+4.8%',
      trend: 'up',
      description: 'Family-friendly with excellent amenities',
    },
    {
      name: 'Green Valley',
      price: '$520,000',
      change: '+5.5%',
      trend: 'up',
      description: 'Established neighborhood with mature trees',
    },
    {
      name: 'Anthem',
      price: '$580,000',
      change: '+7.1%',
      trend: 'up',
      description: 'Gated communities with resort-style living',
    },
  ];

  const insights = [
    {
      title: "Strong Seller's Market Continues",
      description:
        'Las Vegas remains a competitive market with low inventory and high demand, particularly in master-planned communities.',
      highlight: 'Multiple offers are common on well-priced homes',
    },
    {
      title: 'Interest Rates Impacting Affordability',
      description:
        'While rates have stabilized, buyers are being more selective and focusing on move-in ready properties.',
      highlight: 'Pre-approval is essential in this market',
    },
    {
      title: 'New Construction Gaining Momentum',
      description:
        'Several new developments are launching, offering modern amenities and energy-efficient features.',
      highlight: 'Early bird pricing available on select communities',
    },
  ];

  return (
    <section className="section-padding bg-white">
      <div className="container-max">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-3xl md:text-4xl font-bold text-vegas-deep-blue mb-4">
            Las Vegas Market Insights
          </h2>
          <p className="text-lg text-gray-600 max-w-3xl mx-auto">
            Stay informed with the latest Las Vegas real estate market trends, neighborhood data,
            and expert analysis to make confident decisions.
          </p>
        </motion.div>

        {/* Market Stats */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-16">
          {marketStats.map((stat, index) => {
            const Icon = stat.icon;
            const TrendIcon = stat.trend === 'up' ? TrendingUp : TrendingDown;
            return (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                viewport={{ once: true }}
                className="bg-gradient-to-br from-vegas-deep-blue to-vegas-accent-blue rounded-xl p-6 text-white"
              >
                <div className="flex items-center justify-between mb-4">
                  <Icon className="w-8 h-8 text-vegas-gold" />
                  <div
                    className={`flex items-center space-x-1 ${
                      stat.trend === 'up' ? 'text-green-300' : 'text-red-300'
                    }`}
                  >
                    <TrendIcon className="w-4 h-4" />
                    <span className="text-sm font-semibold">{stat.change}</span>
                  </div>
                </div>
                <div className="text-2xl font-bold mb-1">{stat.value}</div>
                <div className="text-vegas-gold text-sm">{stat.label}</div>
              </motion.div>
            );
          })}
        </div>

        {/* Neighborhood Data */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
          className="mb-16"
        >
          <h3 className="text-2xl font-bold text-vegas-deep-blue text-center mb-8">
            Popular Neighborhoods
          </h3>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {neighborhoods.map((neighborhood, index) => {
              const TrendIcon = neighborhood.trend === 'up' ? TrendingUp : TrendingDown;
              return (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, x: index % 2 === 0 ? -20 : 20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                  viewport={{ once: true }}
                  className="bg-gray-50 rounded-xl p-6 border border-gray-200 hover:shadow-lg transition-shadow duration-300"
                >
                  <div className="flex items-center justify-between mb-3">
                    <h4 className="text-xl font-semibold text-vegas-deep-blue">
                      {neighborhood.name}
                    </h4>
                    <div className="flex items-center space-x-1 text-green-600">
                      <TrendIcon className="w-4 h-4" />
                      <span className="text-sm font-semibold">{neighborhood.change}</span>
                    </div>
                  </div>
                  <div className="text-2xl font-bold text-vegas-gold mb-2">
                    {neighborhood.price}
                  </div>
                  <p className="text-gray-600">{neighborhood.description}</p>
                </motion.div>
              );
            })}
          </div>
        </motion.div>

        {/* Market Insights */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
        >
          <h3 className="text-2xl font-bold text-vegas-deep-blue text-center mb-8">
            Expert Market Analysis
          </h3>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {insights.map((insight, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                viewport={{ once: true }}
                className="bg-white rounded-xl p-6 shadow-lg border border-gray-200 hover:shadow-xl transition-shadow duration-300"
              >
                <h4 className="text-xl font-semibold text-vegas-deep-blue mb-3">{insight.title}</h4>
                <p className="text-gray-600 mb-4 leading-relaxed">{insight.description}</p>
                <div className="bg-vegas-gold/10 border-l-4 border-vegas-gold p-3 rounded-r-lg">
                  <p className="text-vegas-deep-blue font-semibold text-sm">
                    💡 {insight.highlight}
                  </p>
                </div>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* CTA */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          viewport={{ once: true }}
          className="text-center mt-12"
        >
          <div className="bg-gradient-to-r from-vegas-deep-blue to-vegas-accent-blue rounded-2xl p-8 text-white">
            <h3 className="text-2xl font-bold mb-4">Ready to Make Your Move?</h3>
            <p className="text-lg mb-6 opacity-90">
              Get personalized market insights and expert guidance for your Las Vegas real estate
              journey.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <a
                href="tel:702-222-1964"
                className="inline-flex items-center justify-center space-x-2 bg-vegas-gold hover:bg-vegas-gold-dark text-vegas-deep-blue px-8 py-3 rounded-lg font-semibold transition-all duration-300 transform hover:scale-105"
              >
                <span>Call Dr. Jan Duffy</span>
                <span className="font-mono">702-222-1964</span>
              </a>
              <a
                href="/market-analysis"
                className="inline-flex items-center justify-center space-x-2 bg-transparent border-2 border-white text-white hover:bg-white hover:text-vegas-deep-blue px-8 py-3 rounded-lg font-semibold transition-all duration-300"
              >
                <span>Get Market Analysis</span>
              </a>
            </div>
          </div>
        </motion.div>
      </div>

      {/* RealScout Listings */}
      <div className="mt-16">
        <RealScoutListings />
      </div>
    </section>
  );
};

export default MarketInsights;

// legacy-sveltekit/src/routes/market-insights/+page.svelte
<script lang="ts">
	import { DollarSign, Calendar, Home, TrendingUp, TrendingDown, BarChart3 } from 'lucide-svelte';

	interface TocItem {
		id: string;
		label: string;
	}

	const tocItems: TocItem[] = [
		{ id: 'key-stats', label: 'Key Stats' },
		{ id: 'trends', label: 'Market Trends' },
		{ id: 'cta', label: 'Request Analysis' }
	];
</script>

<svelte:head>
	<title>Las Vegas Luxury &amp; Relocation Market Insights | Dr. Janet Duffy REALTOR®</title>
	<meta name="description" content="Las Vegas Luxury & Relocation market insights including current median prices, days on market, inventory levels, and trends across key Las Vegas communities." />
	
	<!-- Structured Data -->
	<script type="application/ld+json">
	{
		"@context": "https://schema.org",
		"@type": "WebPage",
		"name": "Las Vegas Market Insights",
		"description": "Current Las Vegas real estate market statistics and trends",
		"url": "https://www.drjanetduffy.com/market-insights"
	}
	</script>
</svelte:head>

<!-- Hero Section -->
<section class="hero-section bg-gradient-to-b from-primary-600 to-primary-700 text-white">
	<div class="container mx-auto px-4 sm:px-6 lg:px-8">
		<div class="max-w-7xl mx-auto py-12 md:py-16">
			<div class="text-center mb-8">
				<h1 class="text-4xl sm:text-5xl md:text-6xl font-bold mb-4">
					Las Vegas Luxury &amp; Relocation Market Trends &amp; Insights
				</h1>
				<p class="text-lg sm:text-xl text-white text-opacity-90 max-w-2xl mx-auto">
					Current Las Vegas real estate statistics and trends
				</p>
			</div>

			<!-- On-page navigation -->
			<nav
				aria-label="Market insights page sections"
				class="mt-10 rounded-full border border-white/20 bg-white/10 px-3 py-2 shadow-sm overflow-x-auto scrollbar-hide"
			>
				<ul class="flex items-center gap-2 text-sm whitespace-nowrap">
					{#each tocItems as item}
						<li>
							<a
								href={`#${item.id}`}
								class="inline-flex items-center rounded-full px-3 py-1.5 text-white/80 hover:text-white hover:bg-white/20 transition-colors no-underline"
							>
								{item.label}
							</a>
						</li>
					{/each}
				</ul>
			</nav>
		</div>
	</div>
</section>

<!-- Key Statistics -->
<section class="section bg-primary-600 text-white" id="key-stats">
	<div class="container mx-auto px-4 sm:px-6 lg:px-8">
		<div class="max-w-7xl mx-auto">
			<div class="grid md:grid-cols-3 gap-8 mb-12">
				<div class="text-center bg-white bg-opacity-10 rounded-xl p-6 backdrop-blur-sm">
					<div class="inline-flex items-center justify-center w-16 h-16 bg-white bg-opacity-20 rounded-full mb-4">
						<DollarSign class="w-8 h-8 text-white" />
					</div>
					<div class="text-4xl md:text-5xl font-bold mb-2">$575K</div>
					<p class="text-white text-opacity-90 mb-2">Median Home Price</p>
					<div class="flex items-center justify-center gap-1 text-green-300">
						<TrendingUp class="w-4 h-4" />
						<span class="text-sm">+8.5% YoY</span>
					</div>
				</div>

				<div class="text-center bg-white bg-opacity-10 rounded-xl p-6 backdrop-blur-sm hover:bg-opacity-15 transition-all duration-300">
					<div class="inline-flex items-center justify-center w-16 h-16 bg-white bg-opacity-20 rounded-full mb-4">
						<Calendar class="w-8 h-8 text-white" />
					</div>
					<div class="text-4xl md:text-5xl font-bold mb-2">19</div>
					<p class="text-white text-opacity-90 mb-2">Days on Market</p>
					<div class="flex items-center justify-center gap-1 text-green-300">
						<TrendingDown class="w-4 h-4" />
						<span class="text-sm">-12% YoY</span>
					</div>
				</div>

				<div class="text-center bg-white bg-opacity-10 rounded-xl p-6 backdrop-blur-sm hover:bg-opacity-15 transition-all duration-300">
					<div class="inline-flex items-center justify-center w-16 h-16 bg-white bg-opacity-20 rounded-full mb-4">
						<Home class="w-8 h-8 text-white" />
					</div>
					<div class="text-4xl md:text-5xl font-bold mb-2">450</div>
					<p class="text-white text-opacity-90 mb-2">Homes for Sale</p>
					<div class="flex items-center justify-center gap-1 text-yellow-300">
						<BarChart3 class="w-4 h-4" />
						<span class="text-sm">Stable Inventory</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Additional Market Data -->
<section class="section bg-white" id="trends">
	<div class="container mx-auto px-4 sm:px-6 lg:px-8">
		<div class="max-w-7xl mx-auto">
			<div class="text-center mb-12">
				<h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-6">What Are the Current Las Vegas Real Estate Market Trends?</h2>
				<p class="text-lg text-gray-700 mb-8 leading-relaxed max-w-4xl mx-auto">
					Current Las Vegas real estate market trends show 2.1% monthly price appreciation, 98% list-to-sale ratio indicating strong seller market conditions, 1.2 months of inventory creating competitive buyer environment, and $285 price per square foot that reflects continued market strength and growth potential throughout the Las Vegas Valley.
				</p>
			</div>
			
			<div class="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
				<div class="card text-center">
					<div class="text-3xl font-bold text-primary-600 mb-2">2.1%</div>
					<p class="text-gray-600 text-sm">Price Appreciation (Monthly)</p>
				</div>
				<div class="card text-center">
					<div class="text-3xl font-bold text-primary-600 mb-2">98%</div>
					<p class="text-gray-600 text-sm">List-to-Sale Ratio</p>
				</div>
				<div class="card text-center">
					<div class="text-3xl font-bold text-primary-600 mb-2">1.2</div>
					<p class="text-gray-600 text-sm">Months of Inventory</p>
				</div>
				<div class="card text-center">
					<div class="text-3xl font-bold text-primary-600 mb-2">$285</div>
					<p class="text-gray-600 text-sm">Price per Sq. Ft.</p>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- CTA Section -->
<section class="section bg-gray-50" id="cta">
	<div class="container mx-auto px-4 sm:px-6 lg:px-8">
		<div class="max-w-4xl mx-auto text-center">
			<h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">Ready to Get Your Personalized Las Vegas Market Analysis?</h2>
			<p class="text-lg text-gray-700 mb-8 leading-relaxed">
				Understand your property's value in today's Las Vegas market. With deep knowledge of current market trends, neighborhood data, and property values, I'll provide comprehensive market analysis to help you make informed real estate decisions whether you're buying, selling, or investing in Las Vegas.
			</p>
			<div class="flex flex-col sm:flex-row gap-4 justify-center">
				<a href="/home-value" class="btn-primary">Get Home Valuation</a>
				<a href="/contact" class="btn-secondary">Schedule Consultation</a>
			</div>
		</div>
	</div>
</section>
